"""Stable provider ports; integrations are intentionally outside the MVP core."""
from typing import Protocol, Any

class ResourceProvider(Protocol):
    def discover(self) -> list[Any]: ...
class ExecutionBackend(Protocol):
    def execute(self, task: Any) -> Any: ...
class ModelProvider(Protocol):
    def models(self) -> list[dict[str, Any]]: ...
class ToolProvider(Protocol):
    def tools(self) -> list[dict[str, Any]]: ...
class TelemetryProvider(Protocol):
    def write(self, record: Any) -> None: ...
class PolicyPlugin(Protocol):
    def allow(self, task: Any, action: str) -> bool: ...
class AgentAdapter(Protocol):
    def events(self) -> list[dict[str, Any]]: ...
